version: "2"
services:
    vault:
      privileged: true
      build: .
      dns:
        - 8.8.8.8
      ports: 
        - "8200:8200"
      volumes:
        - file:/vault/file:rw
        - ./config:/vault/config:rw
        - ./ssl:/vault/ssl:rw
      cap_add:
        - IPC_LOCK
      entrypoint: vault server -config=/vault/config/vault_ssl.json
      restart: always
      depends_on:
        - consul
    consul:
      image: consul:latest
      volumes:
        - data:/consul/data:rw
      environment:
        - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      entrypoint:
        - consul
        - agent
        - -server
        - -data-dir=/consul/data
        - -bootstrap-expect=1
        - -client=0.0.0.0
        - -ui
      ports: 
        - "8500:8500"
      restart: always
volumes:
    file:
    data:
